server:
  port: 8003
spring:
  application:
    name: cloud-zk-payment-service #显示服务名称
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/springcloud?characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useUnicode=true&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  cloud:
    zookeeper:
      connect-string: 192.168.6.91:2181

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.taoyee.cloud.entities

