server:
  port: 8803
spring:
  application:
    name: cloud-stream-rabbitmq-xfz
  cloud:
    stream:
      binders: # 在此处配置要绑定的 rabbitmq 的服务信息
        defaultRabbit:  # 表示定义的名称，用于 binding 整合
          type: rabbit # 消息组件类型
          environment: # 设置 rabbitmq 的相关的环境配置
            spring:
              rabbitmq:
                host: rabbitmq.com  #rabbitmq.com 和localhost 都可以，为何本剧ip:192.168.6.89不行？
                port: 5672
                username: guest
                password: guest
      bindings: # 服务的整合处理
        input: # 这个名字是一个通道的名称
          destination: studyExchange # 表示要使用的 exchange 名称
          content-type: application/json # 设置消息类型，本次为 json, 文本则设置 text/plain
          binder: defaultRabbit # 设置要绑定的消息服务的具体配置
          group: GROUP_A

eureka:
  instance:
    instance-id: cloud-stream-rabbitmq-xfz8803
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7000.com:7000/eureka
      #defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
